# Generated by Django 2.1.5 on 2019-04-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': '"categorias"',
            },
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('cep', models.CharField(max_length=15)),
                ('CPF', models.CharField(max_length=20)),
                ('logradouro', models.CharField(max_length=250)),
                ('bairro', models.CharField(default='Centro', max_length=250)),
                ('numero', models.CharField(max_length=20)),
                ('cidade', models.CharField(default='São Paulo', max_length=200)),
                ('UF', models.CharField(default='SP', max_length=2)),
                ('complemento', models.CharField(max_length=250)),
            ],
            options={
                'db_table': '"customer"',
                'ordering': ['-creation', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('card', models.CharField(max_length=16)),
                ('dv', models.CharField(max_length=3)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neoapp.Costumer')),
            ],
            options={
                'db_table': '"payinfo"',
                'ordering': ['-creation', 'costumer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('preco', models.FloatField(default=10.0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neoapp.Categoria')),
            ],
            options={
                'db_table': '"produtos"',
            },
        ),
        migrations.CreateModel(
            name='ProdutoTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neoapp.Produtos')),
            ],
            options={
                'db_table': '"produto_tags"',
            },
        ),
        migrations.CreateModel(
            name='ProdutoVendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neoapp.Produtos')),
            ],
            options={
                'db_table': '"item_vendas"',
                'ordering': ['vendas', '-produtos', '-valor'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': '"Tags"',
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neoapp.PayInfo')),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neoapp.Costumer')),
            ],
            options={
                'db_table': '"vendas"',
                'ordering': ['-creation', 'costumer', 'status'],
            },
        ),
        migrations.CreateModel(
            name='VendasStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': '"vendas_status"',
            },
        ),
        migrations.AddField(
            model_name='vendas',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neoapp.VendasStatus'),
        ),
        migrations.AddField(
            model_name='produtovendas',
            name='vendas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neoapp.Vendas'),
        ),
        migrations.AddField(
            model_name='produtotags',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neoapp.Tags'),
        ),
    ]
