# Generated by Django 2.1.5 on 2019-05-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='costumer',
            table='"costumer"',
        ),
    ]
