# Generated by Django 2.1.5 on 2019-05-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoapp', '0002_auto_20190506_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='UF',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('PR', 'Paraná'), ('MG', 'Minas Gerais')], default='SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='complemento',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
